global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'envoy_waf'
    metrics_path: /stats/prometheus
    static_configs:
      - targets: ['envoy:9901']

  - job_name: 'management_api'
    metrics_path: /metrics
    static_configs:
      - targets: ['management-api:8082']
